# Generated by Django 5.2 on 2025-06-20 19:30

import App.models
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('first_name', models.CharField(blank=True, default='', max_length=255, null=True)),
                ('user_type', models.CharField(choices=[('parent', 'Parent'), ('nursery', 'Nursery'), ('admin', 'Admin')], default='parent', max_length=20)),
                ('reset_token', models.CharField(blank=True, max_length=100, null=True)),
                ('nursery_request', models.TextField(blank=True, default='', verbose_name='Nursery Request Details')),
                ('parent_request', models.TextField(blank=True, default='', verbose_name='Parent Request Details')),
                ('request_status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=20, verbose_name='Request Status')),
                ('request_created_at', models.DateTimeField(auto_now_add=True, verbose_name='Request Created At')),
                ('username', models.CharField(blank=True, default=App.models.generate_unique_username, max_length=150, null=True, unique=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Nursery',
            fields=[
                ('admin_id', models.OneToOneField(limit_choices_to={'user_type': 'nursery'}, on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('name', models.CharField(max_length=255, verbose_name='Nursery Name')),
                ('address', models.CharField(max_length=255, verbose_name='Nursery Address')),
                ('description', models.TextField(blank=True, default='')),
                ('phone_number', models.CharField(max_length=15, unique=True)),
                ('longitude', models.FloatField(default=0.0)),
                ('latitude', models.FloatField(default=0.0)),
                ('image', models.ImageField(blank=True, null=True, upload_to='nursery_images/')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('rejected', 'Rejected')], default='pending', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Parent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=255, verbose_name='Full Name')),
                ('address', models.CharField(blank=True, default='Unknown', max_length=255)),
                ('phone_number', models.CharField(max_length=15, unique=True)),
                ('job', models.CharField(blank=True, default='Unknown', max_length=255)),
                ('admin_id', models.ForeignKey(blank=True, limit_choices_to={'user_type': 'parent'}, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Child',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('child_name', models.CharField(max_length=100)),
                ('date_of_birth', models.DateField()),
                ('father_mother_name', models.CharField(max_length=100)),
                ('job', models.CharField(blank=True, max_length=100)),
                ('address', models.CharField(blank=True, default='Unknown', max_length=200)),
                ('phone_number', models.CharField(blank=True, max_length=15)),
                ('another_phone_number', models.CharField(blank=True, max_length=15)),
                ('gender', models.CharField(blank=True, choices=[('male', 'Male'), ('female', 'Female')], max_length=10)),
                ('parent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='children', to='App.parent')),
            ],
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('message', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_read', models.BooleanField(default=False)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='App.parent')),
                ('nursery', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='App.nursery')),
            ],
        ),
        migrations.CreateModel(
            name='NurseryParent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('rejected', 'Rejected')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('parent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='App.parent')),
                ('nursery', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='App.nursery')),
            ],
            options={
                'unique_together': {('nursery', 'parent')},
            },
        ),
    ]
