# Generated by Django 5.0.3 on 2025-05-10 21:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='user_type',
            field=models.CharField(choices=[('parent', 'Parent'), ('nursery', 'Nursery'), ('admin', 'Admin')], default='parent', max_length=20),
        ),
    ]
