# Generated by Django 5.2 on 2025-06-20 19:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='nurseryparent',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='nurseryparent',
            name='child',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='App.child'),
        ),
        migrations.AlterUniqueTogether(
            name='nurseryparent',
            unique_together={('nursery', 'parent', 'child')},
        ),
    ]
