# Generated by Django 5.2 on 2025-06-21 01:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0002_alter_nurseryparent_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nursery',
            name='address',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Nursery Address'),
        ),
        migrations.AlterField(
            model_name='nursery',
            name='phone_number',
            field=models.CharField(blank=True, max_length=15, null=True, unique=True),
        ),
    ]
